### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by Anton-beep** [aleshij/YandexGO_Arithmetic_v2#1]
- Весь реализованный ранее функционал работает как раньше, только в контексте конкретного пользователя.
> 19 / 20
> *Я смог создать двух пользователей с одинаковым логином, надо настроить unique в sqlite*

- У кого выражения хранились в памяти - переводим хранение в SQLite. (теперь наша система обязана переживать перезагрузку)
> 20 / 20

- У кого общение вычислителя и сервера вычислений было реализовано с помощью HTTP - переводим взаимодействие на GRPC
> 10 / 10

- за покрытие проекта модульными тестами можно получить бонусные 10 баллов
> 10 / 10

- за покрытие проекта интеграционными тестами можно получить бонусные 10 баллов
> 0 / 10
> *Упоминаний не нашел*

**Comment by Gandalf-Rus** [comment]
в лс написал баллы тут напишу рекомендации и вопросы которые у меня возникли при проверке
**Внимание**, все это все го лишь рекомендации и и не к чему не побуждают и не направлены на то чтобы кого-нибудь обидеть (*мало ли вдруг:)...*)

1. Readme пишут с расширением **.md** так что лучше замени свой readme хотя бы на [этот](https://github.com/aleshij/YandexGO_Arithmetic_v2/files/15138258/Readme.md) (это все твой же реадми просто более читаемый)

2. Я не понял почему в проекте 2 БД
3. не нужно было дважды копировать файл агентов, можно просто дважды запустить один и тот же файл в разных терминалах
4. Агенты по хорошему должны считать чисто мини операции (ну об этом я говорил)
5. Общение клиента с сервером лучше делать не через путь и query *(?var=123&var2=123)* а передавать данные через json в теле
